### ISSUE TITLE
Progress bars for completed tasks should show 100% when resuming

### ISSUE THREAD

**Issue by JinEnMok** [TheHardew/compress_comics#21]
If I stop the script and re-run it, the files that it already converted are correctly identified in the output directory, and we get a `File exists` message under the corresponding progress bar.

However, the progress bar itself reports 0%, and `0/total [00:00<?, ?img/s]` for the files that have already been converted.

Proposal: hide the progress bars altogether for existing files, or set it at 100% and hide the page, time, and img/s counters.

**Comment by TheHardew** [comment]
Yeah, I've been meaning to just switch to plain text after the compression happens, because it's not so error prone when scaling the window later.

I did not know what to do with the amount of images and the rate, I guess it can be hidden, but I thought the time/book was actually useful.

I'll look into it tomorrow

**Comment by TheHardew** [comment]
Now it looks like this:
```
00:01| A cbr.cbr - 26/28 (-1) [MiB] 95%
00:01| B cbz.cbz - 26/28 (-1) [MiB] 95%
100%| Comic books - 53/55 (-3) [MiB] 95%                      | 2/2 [00:03<00:00  1.51s/book]
```

and:
```
00:00| A cbr.cbr
File exists - /tmp/dir/tests/com/A cbr.cbz
00:00| B cbz.cbz
File exists - /tmp/dir/tests/com/B cbz.cbz                                                   
100%| Comic books - 55/55 (0) [MiB] 100%                      | 2/2 [00:00<00:00  6.22book/s]
```

**Comment by TheHardew** [comment]
I guess I'm closing it. Showing "100%" is not necessary, it should be obvious from the fact that there are no errors and it shows the statistics for compressed size.

I'll still have to remove the "100%" and "remaining time" from the "Comic books" bar.

**Comment by TheHardew** [comment]
New version:
```
00:01| pepper&carrot cbr.cbr - 26/28 (-1) [MiB] 95%
00:01| pepper&carrot cbz.cbz - 26/28 (-1) [MiB] 95%
00:02| Comic books - 53/55 (-3) [MiB] 95%                                  | 2/2 [1.29s/book]
```

Fell free to tell me if you have any suggestions

There's still probably a lot to be corrected if any exceptions arise.
