### ISSUE TITLE
Add a flag to compress files in-place

### ISSUE THREAD

**Issue by JinEnMok** [TheHardew/compress_comics#9]
I.e. unpacking, compressing, and then repacking and overwriting the original file, as opposed to writing to a new directory.

**Comment by TheHardew** [comment]
Please check the update. I still need to update the README though.
Usage:
`python compress_comics.py -o`
or
`python compress_comics.py --overwrite`

**Comment by TheHardew** [comment]
It should work, but I didn't want to add it at first since it's risky to overwrite stuff, I don't trust myself to do it perfectly on the first try, so better do it only with things you are prepared to lose.

**Comment by JinEnMok** [comment]
thanks for the update. I figured you didn't want it to be destructive, but this could be useful for testing or singular converts.
